### ISSUE TITLE
With cursor I have to look away from the keyboard to add each character

### ISSUE THREAD

**Issue by bknill** [feiss/aframe-simple-keyboard-component#11]
I'm using this with the cursor component in 0.9.0.

I can easily set the first character, to set the next one I have to look away from the keyboard, and then look on it again to set another character. 

Config:

```
            'super-keyboard' : {  
                font: 'roboto',
                labelColor: darkViolet,
                inputColor: darkViolet,
                imagePath: '/assets/images/',
                keyHoverColor: darkViolet,
                keyPressColor: violet,
                keyBgColor: backgroundViolet,
                keyColor: backgroundViolet,
                show: true
            },
```

Cursor attributes

```
      const cursorAttributes={
        fuse: true,
        fuseTimeout: cursorFuseTimeout,
      }

      const raycasterAttributes = {
        objects: '.clickable',
      }

    recticle.setAttribute('cursor', cursorAttributes)
      recticle.setAttribute('raycaster', raycasterAttributes)
```

**Comment by bknill** [comment]
This is still happening.

I.e. I select a character, with the cursor focused on the keyboard. I then want to select another character, and nothing will select until I completely look away from the keyboard and then look at it again. 

Is there something I can set in the raycaster to let it select another character while still looking at the keyboard? 

Otherwise this will have to be explained to the user but it's ugly.

**Comment by ngokevin** [comment]
fuse cursor isn't supported, also awkward since you have to wait a good amount of time for each char.

if you are focusing on cardboard, most cardboards support click
