### ISSUE TITLE
Interferes with laser-controls

### ISSUE THREAD

**Issue by aziliak** [feiss/aframe-simple-keyboard-component#2]
Whenever I add the keyboard to an existing project that uses laser-controls, the only clicks that register are for the keyboard.  Is there an easy way around this?

**Comment by arthurmougin** [comment]
did you try to only set the keys as interactives objects in the laser component?
the keyboard is not the target you are looking for, just its childs

![image](https://user-images.githubusercontent.com/26094902/43419772-ed613034-940f-11e8-9432-d82144b12946.png)

**Comment by aziliak** [comment]
After looking through the code more, I added "class="keyboard-raycastable" to the entity I was wanting to click on and the issue was solved.  I may end up modifying the code to remove keyboard-raycastable object.

Your comment helped me look in the right direction.  Thanks.
