### ISSUE TITLE
Allow non-VR controls

### ISSUE THREAD

**Issue by maurice-schleussinger** [feiss/aframe-simple-keyboard-component#4]
Bind onto mouse cursor events by default (like https://github.com/etiennepinchon/aframe-material) so we can quickly test functionality in non-VR developer environments.

**Comment by ngokevin** [comment]
Just set `hand: #mouseCursor` whatever the ID is. https://github.com/supermedium/aframe-super-keyboard#api . Will update it to also look for `[cursor]`.
