### ISSUE TITLE
I can't type text on examples using Oculus.

### ISSUE THREAD

**Issue by dmarcos** [feiss/aframe-simple-keyboard-component#7]
I can't see where the click event that the keyboard listens to is emitted in the examples by the controller. Am I missing anything?

**Comment by ngokevin** [comment]
Updated examples to have cursor component (via laser-controls). You'll need to change the `super-keyboard.hand` property to `#hand` to get to work in VR. Ideally, there'd be an auto-switcher component but whatever for now.
