### ISSUE TITLE
the keyboard hide text elements behind it

### ISSUE THREAD

**Issue by arthurmougin** [feiss/aframe-simple-keyboard-component#9]
is there a way to let the text render behind the keyboard image ?

![image](https://user-images.githubusercontent.com/26094902/47620995-59996a00-daf1-11e8-9e57-728fb3c4eb4d.png)

the text behind have this properties : 
`<a-text class="powered" position="0.45 -0.45 0" align="right" wrap-count="35" baseline="bottom" width="0.6" value="my text" color="grey" text=""></a-text>`

**Comment by ngokevin** [comment]
Try set text entity after keyboard in HTML and/or change the Z position of the text.
